spring:
  config:
    import: optional:configserver:http://config-service:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    username: auth-user
    password: auth@123
    url: jdbc:postgresql://auth-db:5432/auth-db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: auth-service