spring:
  cloud:
    config:
      server:
        git:
          uri: http://gitlab.longpxh.tech/root/oj-config-repo.git
          username: oauth2
          password: ${GITLAB_TOKEN}
          default-label: main
          skip-ssl-validation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: false
    hostname: config-service
