spring:
  application:
    name: DB

  datasource:
    url: jdbc:postgresql://localhost:5432/studentTYP
    username: typ
    password: typ123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
