spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://auth-db:5432/oj_core_db
    username: auth-user
    password: auth@123
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    config:
      enabled: false

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
